apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "culvert.fullname" . }}-config
  labels:
    {{- include "culvert.labels" . | nindent 4 }}
data:
  culvert.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
